### ISSUE TITLE
Start SpeechRecognition without wordlist

### ISSUE THREAD

**Issue by havi05** [allan-simon/gdextension-vosk-speech-to-text#2]
Could you please add the possibility to initialise vosk without a word list (additionally).
Maybe the functions could be named:
- init(model)
- init_wordlist(model,wordlist)

**Comment by allan-simon** [comment]
Hello for this I would gladly review a PR , but as I've not worked on godot for a long time, I don't have the environment set up anymore.

**Comment by havi05** [comment]
I have already created the second function (it works). I would create a pr and you can decide what you think of it.
The only problem I have left is that German characters like ä, ö, ü and ß cannot be displayed. I think it is not formatted with utf8. I will try to fix that before I create a pr.
If you have enough time, do you have any idea what the problem could be?

**Comment by havi05** [comment]
I could not find a solution for the incorrectly displayed characters, but the pr implements this feature request.
